# -*- coding: UTF-8 -*-
word_device = {
    "TurnOnTheLight" : 0,
    "TurnTheLightOn" : 0,
    "SwitchOnTheLight" : 0,
    "SwitchTheLightOn" : 0,
    "TurnOnTheTv" : 1,
    "TurnTheTVOn" : 1,
    "SwitchOnTheTV" : 1,
    "SwitchTheTVOn" : 1,
    "TurnOnTheFan" : 2,
    "TurnTheFanOn" : 2,
    "SwitchOnTheFan" : 2,
    "SwitchTheFanOn" : 2,
    "TurnOnTheSoundMachine" : 3,
    "TurnTheSoundMachineOn" : 3,
    "SwitchOnTheSoundMachine" : 3,
    "SwitchTheSoundMachineOn" : 3,
    "TurnOffTheLight" : 4,
    "TurnTheLightOff" : 4,
    "SwitchOffTheLight" : 4,
    "SwitchTheLightOff" : 4,
    "TurnOffTheTv" : 5,
    "TurnTheTvOff" : 5,
    "SwitchOffTheTv" : 5,
    "SwitchTheTvOff" : 5,
    "TurnOffTheFan" : 6,
    "TurnTheFanOff" : 6,
    "SwitchOffTheFan" : 6,
    "SwitchTheFanOff" : 6,
    "TurnOffTheSoundMachine" : 7,
    "TurnTheSoundMachineOff" : 7,
    "SwitchOffTheSoundMachine" : 7,
    "SwitchTheSoundMachineOff" : 7,
    "TurnOnAllTheDevices" : 8,
    "TurnAllTheDevicesOn" : 8,
    "SwitchOnAllTheDevices" : 8,
    "SwitchAllTheDevicesOn" : 8,
    "TurnOffAllTheDevices" : 9,
    "TurnAllTheDevicesOff" : 9,
    "SwitchOffAllTheDevices" : 9,
    "SwitchAllTheDevicesOff" : 9,
    "IsTheLightOn" :10,
    "CanYouTellMeIfTheLightIsOn" :10,
    "IsTheLightTurnOn" :10,
    "IsTheLightSwitchOn" :10,
    "IsTheTvOn" :11,
    "CanYouTellMeIfTheTVIsOn" :11,
    "IsTheTVTurnOn" :11,
    "IsTheTVSwitchOn" :11,
    "IsTheFanOn" :12,
    "CanYouTellMeIfTheFanIsOn" :12,
    "IsTheFanTurnOn" :12,
    "IsTheFanSwitchOn" :12,
    "IsTheSoundMachineOn" :13,
    "CanYouTellMeIfSoundMachineIsOn" :13,
    "IsTheSoundMachineTurnOn" :13,
    "IstheSoundMachineSwitchOn" :13,
    #"GoodBye" : 100 ,
    "SeeYouLater" : 100,
    "GoBackToSkills" : 100
    
}
    
